-- Create the role Data Cloud will use
CREATE or replace ROLE DATACLOUD_ROLE;

-- Grant database/schema access
GRANT USAGE ON DATABASE PRONTO TO ROLE DATACLOUD_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PRONTO TO ROLE DATACLOUD_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE PRONTO TO ROLE DATACLOUD_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE PRONTO TO ROLE DATACLOUD_ROLE;
-- SHOW ROLES
