-- Create the service user (TYPE = SERVICE bypasses the password auth deprecation)
CREATE USER DATACLOUD_PRONTO
  TYPE = SERVICE
  DEFAULT_ROLE = DATACLOUD_ROLE
  DEFAULT_WAREHOUSE = PRONTO;

-- Assign the role
GRANT ROLE DATACLOUD_ROLE TO USER DATACLOUD_PRONTO;
-- DESCRIBE USER DATACLOUD_PRONTO
