-- Create the role Data Cloud will use
CREATE or replace ROLE DATACLOUD_ROLE;

-- Grant database/schema access
GRANT USAGE ON DATABASE PRONTO TO ROLE DATACLOUD_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PRONTO TO ROLE DATACLOUD_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE PRONTO TO ROLE DATACLOUD_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE PRONTO TO ROLE DATACLOUD_ROLE;
-- SHOW ROLES

-- Create the WAREHOUSE and assign the ROLE
CREATE or replace WAREHOUSE PRONTO;
GRANT USAGE ON WAREHOUSE PRONTO TO ROLE DATACLOUD_ROLE;
-- SHOW WAREHOUSES

-- Create the service user (TYPE = SERVICE bypasses the password auth deprecation)
CREATE or replace USER DATACLOUD_PRONTO
  TYPE = SERVICE
  DEFAULT_ROLE = DATACLOUD_ROLE
  DEFAULT_WAREHOUSE = PRONTO;
-- DESCRIBE USER DATACLOUD_PRONTO

-- Assign the role
GRANT ROLE DATACLOUD_ROLE TO USER DATACLOUD_PRONTO;

-- Assign the public key (paste the content of rsa_key.pub, 
-- stripping the -----BEGIN PUBLIC KEY----- header/footer)
ALTER USER DATACLOUD_PRONTO SET RSA_PUBLIC_KEY='paste your key here';
-- DESCRIBE USER DATACLOUD_PRONTO